### ISSUE TITLE
Project complete

### ISSUE THREAD

**Issue by kme012** [Bucknell-Biol364/Biology208tutorial#12]
https://github.com/Bucknell-Biol364/Biology208tutorial/blob/5e1377c83e6258946a92b41bce44651f6200cbd7/Biol_208_Tutorial.Rmd#L1

@KField-Bucknell 
Our project's done!

**Comment by KField-Bucknell** [comment]
This looks really good and I am sure it was a lot of work. It suffers from being a little fragmented because of the different directions that you got from each Prof. 

Do you think it would make sense to split it into three different Rmd files?
