### ISSUE TITLE
Testing Normality with transformation

### ISSUE THREAD

**Issue by jkoss6** [Bucknell-Biol364/Biology208tutorial#2]
https://github.com/Bucknell-Biol364/Biology208tutorial/blob/403ceb2219d0142a66338a2471f775fa08b1c440/Biol_208_Tutorial.Rmd#L77

@KField-Bucknell 

When I log10 transformed the data for petal length the p-value actually got smaller and the data seemed "less normal". Should I have used a different function to transform the data?

**Comment by KField-Bucknell** [comment]
Another common transformation is the square root. Does that help?
