### ISSUE TITLE
Function Error

### ISSUE THREAD

**Issue by kme012** [Bucknell-Biol364/Biology208tutorial#3]
https://github.com/Bucknell-Biol364/Biology208tutorial/blob/59027850c5925657bc9267ca830bb5ad7ddcb350/Biol_208_Tutorial.Rmd#L318

@KField-Bucknell 
I wanted to try to incorporate the human demography data into the tutorial. They gave it to us as the number of people that died in each age class, and I realized that I couldn't just add a new column with the relevant numbers because each row is dependent on the one before it. So I wrote my own functions to do the math to find out the proportion of people still alive in each age class to make a survivorship curve. However, when I try to run the data through, this error pops up:
Error in numStillAlive(fpre1840) : object 'listStillAlive' not found

Google hasn't really been helpful (or at least I don't really know what they're saying on stack), so I was wondering if you could run the code and see what I need to do to get it to work? Thanks!

**Comment by KField-Bucknell** [comment]
Woah. Writing your own function? That is impressive! I'm not sure what the problem is, but this might be a lot easier for you after lab tomorrow when we learn about _dplyr_.
