### ISSUE TITLE
Grading

### ISSUE THREAD

**Issue by jkoss6** [Bucknell-Biol364/Biology208tutorial#4]
https://github.com/Bucknell-Biol364/Biology208tutorial/blob/36b72844c274e88410b1e653737d6385fe241ace/Biol_208_Tutorial.Rmd#L7

@KField-Bucknell 

It is ready to be submitted/graded!

It also would not let me knit it again but I think that's because of how we were walking them through some code chunks. 

@mnr006 @kme012

**Comment by KField-Bucknell** [comment]
Yes, I think that you will need to consider whether you want to use an Rmd or an R script. If an Rmd, do you want to knit it for them?
